# Generated by Django 3.1.7 on 2021-03-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
